import type { MediaItem } from "@shared/types";
import type { Env } from "../env";
import { all, now, stmt, uid } from "../lib/db";
import { ApiError, badRequest } from "../lib/errors";
import { sha256Hex } from "../lib/crypto";

export const MAX_PHOTO_BYTES = 8 * 1024 * 1024;
export const MAX_IMPORT_BYTES = 10 * 1024 * 1024;
const PHOTO_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);

export interface MediaRow {
  id: string;
  kind: "photo" | "signature" | "pdf" | "import";
  r2_key: string;
  filename: string;
  content_type: string;
  size_bytes: number;
  sha256: string;
  caption: string;
  uploaded_by: string;
  vehicle_id: string | null;
  protocol_id: string | null;
  damage_id: string | null;
  attached_at: string | null;
  discarded_at: string | null;
  created_at: string;
}

export function mediaUrl(id: string): string {
  return `/api/media/${id}`;
}

export function toMediaItem(m: MediaRow): MediaItem {
  return {
    id: m.id,
    kind: m.kind,
    filename: m.filename,
    content_type: m.content_type,
    size_bytes: m.size_bytes,
    sha256: m.sha256,
    caption: m.caption,
    created_at: m.created_at,
    url: mediaUrl(m.id),
  };
}

function extFor(type: string): string {
  if (type === "image/jpeg") return "jpg";
  if (type === "image/png") return "png";
  if (type === "image/webp") return "webp";
  if (type === "application/pdf") return "pdf";
  return "bin";
}

/** Stores an uploaded photo or signature in R2 and registers it as staged media. */
export async function stageUpload(
  env: Env,
  userId: string,
  kind: "photo" | "signature",
  file: File | Blob,
  filename: string,
  caption = "",
): Promise<MediaItem> {
  const type = file.type || "application/octet-stream";
  if (!PHOTO_TYPES.has(type)) throw badRequest("media_type");
  if (file.size > MAX_PHOTO_BYTES) throw badRequest("media_too_large", undefined, { max: MAX_PHOTO_BYTES / 1024 / 1024 });
  const bytes = await file.arrayBuffer();
  const hash = await sha256Hex(bytes);
  const id = uid();
  const day = new Date().toISOString().slice(0, 10);
  const key = `${kind}/${day}/${id}.${extFor(type)}`;
  await env.MEDIA.put(key, bytes, { httpMetadata: { contentType: type }, customMetadata: { sha256: hash, uploaded_by: userId } });
  const ts = now();
  await stmt(
    env.DB,
    "INSERT INTO media (id, kind, r2_key, filename, content_type, size_bytes, sha256, caption, uploaded_by, created_at) VALUES (?,?,?,?,?,?,?,?,?,?)",
    id,
    kind,
    key,
    filename.slice(0, 200),
    type,
    file.size,
    hash,
    caption.slice(0, 200),
    userId,
    ts,
  ).run();
  return {
    id,
    kind,
    filename,
    content_type: type,
    size_bytes: file.size,
    sha256: hash,
    caption,
    created_at: ts,
    url: mediaUrl(id),
  };
}

/** Stores generated bytes (PDF) as attached media. Returns the media row id. */
export async function storeGenerated(
  env: Env,
  opts: { kind: "pdf" | "import"; bytes: Uint8Array; contentType: string; filename: string; userId: string; vehicleId?: string | null; protocolId?: string | null },
): Promise<string> {
  const id = uid();
  const hash = await sha256Hex(opts.bytes);
  const day = new Date().toISOString().slice(0, 10);
  const key = `${opts.kind}/${day}/${id}.${extFor(opts.contentType)}`;
  await env.MEDIA.put(key, opts.bytes, { httpMetadata: { contentType: opts.contentType }, customMetadata: { sha256: hash } });
  const ts = now();
  await stmt(
    env.DB,
    "INSERT INTO media (id, kind, r2_key, filename, content_type, size_bytes, sha256, uploaded_by, vehicle_id, protocol_id, attached_at, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
    id,
    opts.kind,
    key,
    opts.filename,
    opts.contentType,
    opts.bytes.byteLength,
    hash,
    opts.userId,
    opts.vehicleId ?? null,
    opts.protocolId ?? null,
    ts,
    ts,
  ).run();
  return id;
}

/**
 * Loads staged (not yet attached, not discarded) media by id and checks the kind.
 * Scoped to the uploader so evidence cannot be pulled from another user's session.
 */
export async function loadStaged(env: Env, ids: string[], kind: "photo" | "signature", userId: string): Promise<MediaRow[]> {
  if (!ids.length) return [];
  const unique = [...new Set(ids)];
  const byId = new Map<string, MediaRow>();
  // D1 allows 100 bound parameters per statement and two are spent on kind and uploader.
  for (let i = 0; i < unique.length; i += 90) {
    const slice = unique.slice(i, i + 90);
    const rows = await all<MediaRow>(
      env.DB,
      `SELECT * FROM media WHERE id IN (${slice.map(() => "?").join(",")}) AND kind = ? AND uploaded_by = ? AND attached_at IS NULL AND discarded_at IS NULL`,
      ...slice,
      kind,
      userId,
    );
    for (const r of rows) byId.set(r.id, r);
  }
  if (byId.size !== unique.length) throw new ApiError(400, "media_not_found");
  // Keep the caller's order so photo captions and damage grouping stay predictable.
  return unique.map((id) => byId.get(id)!);
}

export function attachStatements(
  db: D1Database,
  media: MediaRow[],
  target: { vehicle_id: string; protocol_id?: string | null; damage_id?: string | null },
): D1PreparedStatement[] {
  const ts = now();
  return media.map((m) =>
    stmt(
      db,
      "UPDATE media SET vehicle_id = ?, protocol_id = ?, damage_id = ?, attached_at = ? WHERE id = ?",
      target.vehicle_id,
      target.protocol_id ?? null,
      target.damage_id ?? null,
      ts,
      m.id,
    ),
  );
}

export async function mediaForProtocol(env: Env, protocolId: string): Promise<MediaRow[]> {
  return all<MediaRow>(env.DB, "SELECT * FROM media WHERE protocol_id = ? AND discarded_at IS NULL ORDER BY created_at", protocolId);
}

export async function mediaForDamage(env: Env, damageId: string): Promise<MediaRow[]> {
  return all<MediaRow>(env.DB, "SELECT * FROM media WHERE damage_id = ? AND discarded_at IS NULL ORDER BY created_at", damageId);
}
